name: earthcube-jupyter-environment
channels:
  - conda-forge
  - trentonoliphant
dependencies:
  - python
  - ipyparams
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - ipywidgets
  - owslib
  - geojson
  - shapely
  - geopandas
  - geojsonio
  - gdal
  - geos
  - lxml
  - requests
  - tqdm
  - holoviews
  - papermill
  - SPARQLWrapper
  -  pathlib