name: earthcube-jupyter-environment
channels:
  - conda-forge
  - trentonoliphant
dependencies:
  - python
  - psutil
  - dill
  - pandas
  - plotly
  - scikit-learn
  - partd
  - ipywidgets
  - lxml
  - requests
  - papermill
  - SPARQLWrapper
  - pathlib
  - minio
  - pip:
    - nbgitpuller
    - ipyparams
    - httpimport

